In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"c:\Users\Jeevan\Downloads\MedicalReviews.csv")

In [3]:
df.head()

,Drug Name,Condition,User,Date,Rating,Content
0,Abilify,Bipolar Disorder,Jay...,9-Jun-20,8,"""I just started this Abilify at a 5mg dose and..."
1,Abilify,Bipolar Disorder,Andrea,24-Aug-20,8,"""I've been struggling with bipolar II my whole..."
2,Abilify,Bipolar Disorder,Ben,14-Dec-19,10,"""Been on every BiPolar med known. Finally tri..."
3,Abilify,Bipolar Disorder,Anony...,18-Oct-19,10,"""I feel like a new woman on Abilify! I have Bi..."
4,Abilify,Bipolar Disorder,Parli...,25-Jan-20,10,"""I am diagnosed with Bipolar 1 and in my 20s s..."

In [4]:
len(df)

280012

In [5]:
len(df['Drug Name'].unique())

1022

In [6]:
len(df['Condition'].unique())

966

In [7]:
df.columns

Index(['Drug Name', 'Condition', 'User', 'Date', 'Rating', 'Content'], dtype='object')

In [8]:
df= df[['Drug Name', 'Condition','Rating', 'Content']]
df.head()

,Drug Name,Condition,Rating,Content
0,Abilify,Bipolar Disorder,8,"""I just started this Abilify at a 5mg dose and..."
1,Abilify,Bipolar Disorder,8,"""I've been struggling with bipolar II my whole..."
2,Abilify,Bipolar Disorder,10,"""Been on every BiPolar med known. Finally tri..."
3,Abilify,Bipolar Disorder,10,"""I feel like a new woman on Abilify! I have Bi..."
4,Abilify,Bipolar Disorder,10,"""I am diagnosed with Bipolar 1 and in my 20s s..."

In [9]:
df.dropna(subset=['Drug Name', 'Condition', 'Rating', 'Content'])

,Drug Name,Condition,Rating,Content
0,Abilify,Bipolar Disorder,8,"""I just started this Abilify at a 5mg dose and..."
1,Abilify,Bipolar Disorder,8,"""I've been struggling with bipolar II my whole..."
2,Abilify,Bipolar Disorder,10,"""Been on every BiPolar med known. Finally tri..."
3,Abilify,Bipolar Disorder,10,"""I feel like a new woman on Abilify! I have Bi..."
4,Abilify,Bipolar Disorder,10,"""I am diagnosed with Bipolar 1 and in my 20s s..."
...,...,...,...,...
280007,60-Second Fluoride Foam,Prevention of Dental Caries,1,"Pro-Den Rx (fluoride)""Makes your mouth very dr..."
280008,60-Second Fluoride Foam,Prevention of Dental Caries,9,"""Been using for a couple of weeks and sensitiv..."
280009,60-Second Fluoride Foam,Prevention of Dental Caries,2,"""It is extreme difficult to use because the tu..."
280010,60-Second Fluoride Foam,Prevention of Dental Caries,9,"""Using in trays post-radiation, easier to fill..."
280011,60-Second Fluoride Foam,Prevention of Dental Caries,8,"Denta 5000 Plus (fluoride)""I'm wondering if it..."

In [10]:
df.Rating.value_counts()

Rating
10                     76621
1                      50083
9                      37267
8                      27019
No rating available    20829
7                      13854
5                      12851
2                      12773
3                      11086
6                       9783
4                       7845
Name: count, dtype: int64

In [11]:
df = df[df["Rating"] != "No rating available"]

In [12]:
df.isnull().sum()

Drug Name    1
Condition    1
Rating       1
Content      1
dtype: int64

In [13]:
df= df.dropna()
len(df)

259182

In [14]:
df.shape

(259182, 4)

In [15]:
#sample 5000 rows

df =df.sample(500)
df.shape

(500, 4)

### Convert the text into list

In [16]:
text = df['Content'].astype('str').tolist()

In [17]:
text

['Mirena (levonorgestrel)"I went to have the Mirena IUD removed 1 1/2 years after placement and my ob/gyn couldn\'t find it to remove it. I have had an ultrasound that turned up nothing and now need an abdominal xray to see if it can be located that way. My insurance won\'t cover any of it until my deductible is met,  so I have to come up with $1000 just to find out, and if they find it, I\'ll need surgery. This "migration and spontaneous expulsion" are more common than the company says. "',
 '"I read all the negative reviews out there before taking this medicine. Of course I was scared out my mind after reading some of the stories but I can tell you, you\'ll be fine. I\'ve had dry lips and skin but besides that, just a clear face so far. (3 months in)"',
 'Remeron (mirtazapine)"Remeron helped my anxiety, but came with side effects. The worst was an uncontrollable appetite and subsequent weight-gain. But everyone is different."',
 'Actos (pioglitazone)"Effective. However, because of issues with possible Bladder Cancer reports, my new Endocrinologist immediately took me off Actos. Also, nausea and vomiting side effects."',
 'Toradol (ketorolac)"I have been given this medication countless times and I\'m yet to have it EVER work."',
 'Wellbutrin (bupropion)"I\'ve been taking Bupropion 1 pill 150mg once a day for anxiety and depression for a month and it hasn\'t really been working. I feel the same way. The first day I felt that it limited my brain somehow, but that was all. And I find myself not being able to sleep at all at night ever since I started taking it. I\'ve been sleeping 2-3 hours. Maybe I should take a higher dose or change medication."',
 '"Excedrine worked better than the hydrocodone for pain from rotator cuff surgery. I threw them away."',
 '"I started off on 25 mg.  Didn’t work.  Then my doctor upped it to 50 mg.  Still didn’t work.  Am now on 100 mg.  Worked good for about one week and now up till 4 or 5 am.  I wake up about 10 - 11 am and I am out of it for about an hour.  I get out of bed and can’t get anything done because I feel so fatigued.  Feeling very frustrated."',
 'AndroGel (testosterone)"An intro: I was dealt a traumatic brain injury that landed me in a coma for 19 days some years back. I\'ve faced issues such as anger, paranoia, suspicion so bad. I wouldn\'t trust my own doctor! That went on for well \'over\' a decade before I heard about Low T. Then I researched, arranged an appointment, had lab work done to find out Low and Behold; I was dealing with a case of Low T, on a big scale. Within the 1st 2 weeks of therapy, differences were like night and day! I honestly have not felt this good, or more with life in general since being on Androgel. I\'m finishing up month number five with regular lab tests and point blank: I feel great! More energy with a tremendous relief of many symptoms."',
 '"I am on day 5 of taking this medication it is the generic of Wellbutrin XL and it has been life changing. I have tons of energy and motivation. I can\'t believe I was never told about this before. I haven\'t felt this good since I was a kid. No bad side effects at all so far"',
 '"I started getting terrible cystic acne on my chin and jaw area in my early twenties - I had never had acne prior. My dermatologist prescribed this doxycycline and ~3 months later my face was cleared. Yes it takes awhile to make a difference but it worked."',
 'Wellbutrin (bupropion)"Wellbutrin worked for me, was actually pretty much a lifesaver. Tried Zoloft and buspar and effexor, all didn\'t work too well. However this med does have side effects like increase anxiety, but apart from that I haven\'t experienced much else. It calms me down and makes me feel like the old me when I was a kid. Confident and happy."',
 '"AMAZING!\n\nWithin 4 days I could see a difference in my  skin.The plaques were starting to fade,the redness and itchiness GONE!\n\nIt has been exactly one week since I started using the spray and I no longer have psoriasis.."',
 '"I have been on Escitalopram for like 3 months now and it’s been incredible on my symptoms from OCD. Although sometimes the intrusive thoughts take place, the good new is that I am more capable to ignore them and go past to them. Definitely a good drug that’ve worked with me and i’m looking forward to see the following results."',
 'Depo Provera (medroxyprogesterone)"This is just me but first I started on pills which  made me nauseous and gave me bad anxiety so I stop taking them for 3 months. May 10th I choose the depo provera injection, my doctor didn’t show all the side effects it says on google. I’ve been constantly nauseous everyday unable to do activities out because of how nauseous I feel sometimes to the point where I throw up, I’m miserable these birth controls don\'t mix well with my body. Now i’m just waiting for it to wear off so I can enjoy my summer. For some people its great tho, this just my experience ."',
 '"I am 18 years old and I got prescribed this to lose weigh.t I did not know anything about this medication and I started taking it 2 times a day I only took it for 1 day because I started leaking out orange oils and I honestly didn’t like it. I had an accident on the second day. I don’t like this side effect. I don’t think this is for me I am going to wait a while to try it again when I start working out and going to he gym and eating health bc right now I’m on vacation and I want to be able to enjoy it without the orange oils"',
 '"I love Zyprexa! Been on it four years. Before I couldn\'t sleep or eat! I will say I have put on weight and I would suggest eating every four to five hours because the hunger can be overwhelming sometimes. But I have slept so much better and oddly enough,  I feel happier!"',
 '"Poison ivy caused my skin rash so I went to Urgent Care.  The nurse practitioner prescribed a 14 day regimen.  4 days 60mg, 5 days 40mg, 5 days 20mg.  My blood pressure went up to 190/124 with a pulse rate of 150!!!  I just stopped after 2 days.  Blood pressure back to normal.  And poison ivy rash is much improved after only 2 days of taking.  Problems:  I told the nurse practitioner that I had blood pressure and an over large prostate, that I was taking medication for both issues.  Losartan for blood pressure.  Finasteride for prostate.  She told me no problem.  I found out later that prednisone decreases the efficiency of both Losartan and Finasteride.  Prednisone worked fast and great for the poison ivy.  BUT the side effects, for me, were LIFE THREATENING.  Not for me.  And be careful if you have high blood pressure, diabetes or prostate problems.  I thank God that I stopped the medication after only 2 days."',
 'Seroquel (quetiapine)"This medication is adequate compared to others in its class, despite it still causing significant side effects such as weight gain (which is very undesirable). At first, this medicine seemed very strong and made me \'zombie-like\' (e.g. slow, unemotional, sleepy) but after a couple of days these were significantly improved. I was on a dose of up to 75mg, and as far as the effects of each individual dose; 25mg help with sleep and \'anger management\', 50mg increased my hunger (a lot) and 75mg helped a little more with anxiety and emotional stability."',
 'Junel Fe 1/20 (ethinyl estradiol / norethindrone)"I have been on and off this birth control for years. From ages 16-18, then took a break for about a year, and then from ages 19-(almost )21. I honestly didn’t know what to expect coming off of this BC again, since the only time I had been off it I was doing active duty military training. I assumed the change in anxiety, weight loss, etc. was because I was in a unique/stressful environment I’d never experienced before. However, after getting off of it once again, I can say this birth control worsened the feelings of mental illness. I wish I hadn’t taken it for so long. I’ve been so insecure, had zero sex drive whatsoever, and felt bloated/overweight constantly. My anxiety and mood swings reached their peaks while taking this. It was a struggle to lose weight while taking this, even with exercise & eating in a calorie deficit. My joints would swell, and I’d still experience all the feelings of periods while taking this without the bleeding. It did seem to help curb my acne though."',
 'Percocet 10/325 (acetaminophen / oxycodone)"Great for chronic pain. Surgery went great, but now I have bad bursitis. These have been a lifesaver, as I have gone back to work and hope to be retiring soon. GREAT-Great."',
 'Spiriva (tiotropium)"I have been using spiriva for about 2 months.  I find my breathing has greatly improved.  I\'m not using my albuterol several times a day anymore, maybe a couple of times a week.  The only thing I have noticed is that I am getting severe muscle cramps in the front of my lower legs.  This happens mostly at night when I go to bed.  Has anyone else noticed this problem?"',
 '"Had a bout of paternal post-natal anxiety and depression (probably a triggering of latent c-PTSD from childhood). I then tried two different SSRIs for 3 weeks each - both made me so drowsy and didn’t relieve any of the major symptoms I was having. Dr put me on desvenlafaxine (50mg) and Quietapine (25mg at night) and within a week I was back to my normal happy self - have been this way for 6 months now and it’s given me the mental strength to go through psychotherapy, which will continue for probably another 6-12 months. This drug (or this combo) saved my life for sure. No major side effects (harder to orgasm, but only slightly). Able to be the husband and parent that I want to be, and that my family deserve."',
 '"Singulair has been a life saver for me.  I am a newly diagnosed asthmatic which had become debilitating.  I was put on a course of prednisolone to relieve symptoms, then doctor tried to control asthma with inhalers.  Couldn\'t get under control with only the inhalers so was prescribed Singulair.  It is amazing, I hardly use my reliever. Before I was using anything up to 40 times a day.  Hayfever symptoms reduced also.  Able to run again, I\'d reached the point where I could hardly walk never mind run.  Now I\'m starting to get my life back."',
 'Orudis (ketoprofen)"I have taken this product for headaches, backaches and toothaches and having tried Motrin, Extra Strength Tylenol, and Aleve for these issues in the past I would give Orudis KT the highest rating of the OTC pain medications."',
 '"This has helped a lot for my daughter\'s hallucinations. She was not diagnosed with schizophrenia, so her hallucinations are related to either her epilepsy or something else. There have been a couple of times where she stopped taking it because she felt better, but then the hallucinations would come back. She had to go on the highest dose after she stopped taking it the first time, so if you find this works for you or a loved one, just make sure they don\'t stop abruptly."',
 'Augmentin (amoxicillin / clavulanate)"My daughter has had multiple middle ear infections. She was put on Augmentin for the last infection. After two days on this medication, she had severe diarrhea and a yeast infection. We called the doctor and had them switch her to something different."',
 '"Terrible Bloating, cramping diarrhea, brain zaps, irritability, anger and rage."',
 '"Latuda worked great at removing my depression and delusional thinking.\nI took it for 2 weeks and had to stop taking it because the side effects were unbearable for me. Painful bloating/ sore breast/ headaches. These side effects I was trying to endure but I got close to calling an ambulance one night before I decided I just couldn’t keep taking Latuda as prescribed (20mg a day). \nNow I been trying to get off and headache is terrible however the rest of the side effects have left me :) and I can eat again. I been using CBD about 300mg a day to help with the headache. It’s helpful and the pain is decreasing. I wished Latuda were have worked. \nI’m keeping the rest of the pills for when paranoia gets out of control. Maybe just use it in the future to ground me when my symptoms get out of hand (it happens 2 or 3 times a year). But I’ll probably just take a few doses and stop it. The side effects are awful otherwise I would have stayed on it"',
 'Percocet 10/325 (acetaminophen / oxycodone)"Foot pain gone. I can walk with out limping."',
 '"I started on 50mg 2 weeks ago and literally on day 2 I felt the fog starting to clear. I was put on these due to depression and anxiety but they\'ve also cleared my migraines too. I haven\'t had one the whole time I\'ve been on it! I have been so much more upbeat, don\'t overthink everything as much and I feel much happier. Even my fiance has mentioned how much difference he has noticed. I was VERY sceptical about taking anti-depressants after trying to \'get myself better\' for years but now I wish I would have done it sooner."',
 'Metadate CD (methylphenidate)"My 5 year old has been on this medication for about 2 weeks now we switched him from Adderall to this because Adderall had to many side effects but other than the side effects he did really well at first. So we switched to Medadate we had high hopes that we found the right medicine for him but we saw no response at all his behavior on the medicine was as if he was not on it. We moved his dose up to 20 yesterday I hope this will help or else we have to try something else."',
 '"This drug ruined my life. It made me delusional, paranoid, aggressive, short tempered. As a result I lost my partner, my job and my house. Don\'t take it!"',
 '"While the antibiotic combo sulfamethoxazole with trimethoprim drug did the trick for my staph infection it wasn’t without a terrible time. I had a panic attack and confusion while I was driving with my pregnant wife. I knew it wasn’t a stroke but it still scared me enough to go straight to the E.R. to get checked out. My anxiety was through the roof my entire time I was on the medication. I knew the medication was causing this so I used breathing exercises to get me through my 10 days. I will never take this stuff again."',
 '"Took mirtazapine for probably around 6 months and it was horrible, didn’t help depression or anxiety at all just makes you put on weight, mood swings, being rude to people and constantly being tired enough to sleep for 12+ hours… no thanks. I’m on venlafaxine now and works wonders so far!"',
 '"I find it alleviates my joint pain. I do suffer from muscle cramps on my right arm, pain in my left side (rib area) and stiffness, pain in the left side of my neck and pins and needles in my left arm. I also get very fatigued from time to time. I also suffer from symptoms of a UTI on and off."',
 '"I got the implant on January 1st of this year and I have lost weight I weighed 125 pounds and I now weigh 113. I can\'t even tell its inserted in my arm and I still have a very high sex drive. I had tried birth control before this and I would forget to take the pill well with this I don\'t have to worry about talking a pill. I highly recomend this I had my period the first month but now I don\'t have it at all. I don\'t get bad cramps or anything. So far I haven\'t had any problems with it.!"',
 '"The only medicine I\'ve tried for my benzodiazepine withdrawal, out of countless psychiatric meds and supplements, to help at all versus benzo withdrawal. Helps me feel more like myself. Also calms my anxiety quite a bit. Hoping this doesn\'t backfire like benzos themselves did, but so far, a life-saver. Taking just 100mg every 4-5 hours."',
 'Augmentin (amoxicillin / clavulanate)"After taking my second Augmentin pill I had horrible nausea, vomiting and diarrhea. I ended up in the hospital for severe dehydration."',
 '"Nexplanon made me gain over 30Ibs. I get ridiculous cravings, crazy mood swings, and all I ever want to do is sit and watch TV since getting it in. I\'ve never had any other kind of birth control, besides the earlier version Implanon, which I thought was better, but still had its flaws, but the hubby and I are considering a vasectomy because my experience with this birth control.\n\nSide effects: Major weight gain, cravings, it made me feel hungrier than I actually was, cramping, boob tenderness to where I thought I may have gotten pregnant, suicidal thoughts, and weird bleeding patterns. \n\nI got it out about 3 weeks ago, and felt a boost in my mood the day after. Still haven\'t been able to drop any weight though."',
 'VESIcare (solifenacin)"Went from having to get up 3 times each night to urinate to only once each night!  Has made for a much more restful nights sleep!  Great medicine."',
 '"I am using this medication as an alternative to Flagyl. I found out about this medication on the internet to treat trichomoniasis and it definitely beats Flagyl\'s metallic taste. Started working within minutes of first dose. Wish the doctor would have told me sooner. I am experiencing some mild itching and more frequency in bowel movements."',
 'Robaxin (methocarbamol)"I\'ve been on Robaxin since 3/11 when I suffered neck/shoulder injury/trauma and a compression fracture in my lower back due to an auto accident. I take it in conjunction with Lortab 10/500 for muscle spasms and pain. It has helped with pain relief. I can continue to drive for work which I drive in excess of 25,000 miles per year. It seems to have little if any side effects."',
 '"I started Requip 1 mg at bedtime.  It worked great for 3-4 months.  My Dr increased the dosage so I now take 3 mg at bedtime.  Again, it worked great for a few months, and then the symptoms reappeared.  The Requip is better than nothing, but I was up pacing the floors when I should have been sleeping.  My husband suggested acupuncture, and that has made a huge difference.  I take the Requip 3 mg with 3 saltines to prevent nausea and vomiting.  I have an acupuncture treatment every 2 weeks, and no problems when I go to bed."',
 'Remicade (infliximab)"Came down with severe UC in November 2021. 67yrs old. Took mesalamine with no results after 30 days. Started Azathioprine in March of 2022. No relief. Took prednisone for 6 weeks. Seemed to knock it down some. Started taking Remicade infusions in April 2022. Had my 4th and last infusion in July 2022. \nBy mid August I was hospitalized for 3 weeks with bacterial pneumonia, Histoplasmosis, and sepsis. A very near death experience. Brought on by immunosuppressive drugs.\n I fired the doctor that prescribed all the immune suppressing drugs. \n My new GI doctor won’t prescribe Remicade  for me (even though he called it the gold standard for UC treatment.\n I would suggest NEVER, NEVER, NEVER take remicade \n I’m currently in remission. Taking both Messalamine Canasa and Messalamine Lialda daily for life I’m told. \n So far so good."',
 'Vicoprofen (hydrocodone / ibuprofen)"Vicoprofen is the most effective med I have ever taken for the severe chronic pain I suffer due to multiple conditions from surgeries, aneurysms, and bone disease.  Not prescribed now by most doctors,  due to excessive abuse some people.  Those of us who continue to suffer,  just have to deal with our crippling pain."',
 '"Update-tolerating Votrient 400mg. Last 2 scans status quo. Diarrhea controlled with immodium. Pattern of a couple good weeks followed by fatigue and general awful feeling. Medicinal marijuana has been a godsend for these bad times. Almost like setting a reset button both mentally and physically. Only do it when I feel awful and won\'t be leaving the house."',

In [18]:
len(text)

500

### Create Metadata

In [19]:
metadata = df[['Drug Name', 'Condition', 'Rating']].to_dict(orient="records")

In [20]:
metadata

[{'Drug Name': 'Levonorgestrel', 'Condition': 'Birth Control', 'Rating': '1'},
 {'Drug Name': 'Isotretinoin', 'Condition': 'Acne', 'Rating': '9'},
 {'Drug Name': 'Mirtazapine', 'Condition': 'AnxietyOff-label', 'Rating': '2'},
 {'Drug Name': 'Pioglitazone', 'Condition': 'Diabetes, Type 2', 'Rating': '1'},
 {'Drug Name': 'Ketorolac', 'Condition': 'Pain', 'Rating': '1'},
 {'Drug Name': 'Bupropion', 'Condition': 'Depression', 'Rating': '1'},
 {'Drug Name': 'Vicodin', 'Condition': 'Pain', 'Rating': '1'},
 {'Drug Name': 'Doxepin', 'Condition': 'Insomnia', 'Rating': '1'},
 {'Drug Name': 'Testosterone',
  'Condition': 'Hypogonadism, Male',
  'Rating': '10'},
 {'Drug Name': 'Bupropion', 'Condition': 'Depression', 'Rating': '10'},
 {'Drug Name': 'Doxycycline', 'Condition': 'Acne', 'Rating': '10'},
 {'Drug Name': 'Bupropion',
  'Condition': 'Major Depressive Disorder',
  'Rating': '9'},
 {'Drug Name': 'Clobex', 'Condition': 'Psoriasis', 'Rating': '10'},
 {'Drug Name': 'Escitalopram',
  'Condition': 'Obsessive Compulsive DisorderOff-label',
  'Rating': '9'},
 {'Drug Name': 'Medroxyprogesterone',
  'Condition': 'Birth Control',
  'Rating': '4'},
 {'Drug Name': 'Orlistat',
  'Condition': 'Weight Loss (Obesity/Overweight)',
  'Rating': '2'},
 {'Drug Name': 'Olanzapine', 'Condition': 'InsomniaOff-label', 'Rating': '10'},
 {'Drug Name': 'Prednisone', 'Condition': 'Skin Rash', 'Rating': '1'},
 {'Drug Name': 'Quetiapine',
  'Condition': 'Borderline Personality DisorderOff-label',
  'Rating': '7'},
 {'Drug Name': 'Junel', 'Condition': 'Birth Control', 'Rating': '2'},
 {'Drug Name': 'Oxycodone and acetaminophen',
  'Condition': 'Chronic Pain',
  'Rating': '10'},
 {'Drug Name': 'Tiotropium', 'Condition': 'COPD, Maintenance', 'Rating': '9'},
 {'Drug Name': 'Desvenlafaxine',
  'Condition': 'Post Traumatic Stress DisorderOff-label',
  'Rating': '10'},
 {'Drug Name': 'Singulair',
  'Condition': 'Asthma, Maintenance',
  'Rating': '10'},
 {'Drug Name': 'Ketoprofen', 'Condition': 'Pain', 'Rating': '9'},
 {'Drug Name': 'Risperdal', 'Condition': 'Schizophrenia', 'Rating': '10'},
 {'Drug Name': 'Amoxicillin and Clavulanate',
  'Condition': 'Otitis Media',
  'Rating': '6'},
 {'Drug Name': 'Viibryd', 'Condition': 'Depression', 'Rating': '1'},
 {'Drug Name': 'Latuda', 'Condition': 'Bipolar Disorder', 'Rating': '6'},
 {'Drug Name': 'Oxycodone and acetaminophen',
  'Condition': 'Pain',
  'Rating': '10'},
 {'Drug Name': 'Sertraline', 'Condition': 'Depression', 'Rating': '10'},
 {'Drug Name': 'Methylphenidate', 'Condition': 'ADHD', 'Rating': '5'},
 {'Drug Name': 'Effexor', 'Condition': 'Depression', 'Rating': '1'},
 {'Drug Name': 'Sulfamethoxazole and trimethoprim',
  'Condition': 'Bacterial Infection',
  'Rating': '3'},
 {'Drug Name': 'Mirtazapine', 'Condition': 'AnxietyOff-label', 'Rating': '1'},
 {'Drug Name': 'Rinvoq', 'Condition': 'Rheumatoid Arthritis', 'Rating': '7'},
 {'Drug Name': 'Nexplanon', 'Condition': 'Birth Control', 'Rating': '10'},
 {'Drug Name': 'Gabapentin',
  'Condition': 'Alcohol WithdrawalOff-label',
  'Rating': '10'},
 {'Drug Name': 'Amoxicillin and Clavulanate',
  'Condition': 'Bacterial Infection',
  'Rating': '1'},
 {'Drug Name': 'Nexplanon', 'Condition': 'Birth Control', 'Rating': '1'},
 {'Drug Name': 'Solifenacin', 'Condition': 'Urinary Frequency', 'Rating': '9'},
 {'Drug Name': 'Clindamycin',
  'Condition': 'Bacterial Vaginosis',
  'Rating': '9'},
 {'Drug Name': 'Methocarbamol', 'Condition': 'Muscle Spasm', 'Rating': '7'},
 {'Drug Name': 'Requip', 'Condition': 'Restless Legs Syndrome', 'Rating': '6'},
 {'Drug Name': 'Infliximab', 'Condition': 'Ulcerative Colitis', 'Rating': '1'},
 {'Drug Name': 'Hydrocodone and ibuprofen',
  'Condition': 'Pain',
  'Rating': '10'},
 {'Drug Name': 'Votrient', 'Condition': 'Renal Cell Carcinoma', 'Rating': '9'},
 {'Drug Name': 'Galcanezumab',
  'Condition': 'Cluster Headaches',
  'Rating': '10'},
 {'Drug Name': 'Dulcolax', 'Condition': 'Constipation', 'Rating': '7'},
 {'Drug Name': 'Sulfamethoxazole and trimethoprim',
  'Condition': 'Urinary Tract Infection',
  'Rating': '10'},
 {'Drug Name': 'Junel', 'Condition': 'Birth Control', 'Rating': '2'},
 {'Drug Name': 'Duloxetine', 'Condition': 'Depression', 'Rating': '4'},
 {'Drug Name': 'Hydroxyzine', 'Condition': 'Anxiety', 'Rating': '8'},
 {'Drug Name': 'Amiodarone',
  'Condition': 'Ventricular Tachycardia',
  'Rating': '10'},
 {'Drug Name': 'Ambien', 'Condition': 'Insomnia', 'Rating': '7'},
 {'Drug Name': 'Rivaroxaban',
  'Condition': 'Pulmonary Embolism',
  'Rating': '3'},
 {'Drug Name': 'Plan B',
  'Condition': 'Emergency Contraception',
  'Rating': '5'},
 {'Drug Name': 'Ocrelizumab',
  'Condition': 'Multiple Sclerosis',
  'Rating': '1'},
 {'Drug Name': 'Venlafaxine',
  'Condition': 'Major Depressive Disorder',
  'Rating': '8'},
 {'Drug Name': 'Yaz 28', 'Condition': 'Birth Control', 'Rating': '10'},
 {'Drug Name': 'Zoloft', 'Condition': 'Panic Disorder', 'Rating': '8'},
 {'Drug Name': 'Caplyta', 'Condition': 'Schizophrenia', 'Rating': '1'},
 {'Drug Name': 'Amitriptyline',
  'Condition': 'InsomniaOff-label',
  'Rating': '8'},
 {'Drug Name': 'Pristiq', 'Condition': 'Depression', 'Rating': '10'},
 {'Drug Name': 'Depo-Provera', 'Condition': 'Birth Control', 'Rating': '9'},
 {'Drug Name': 'Sulfamethoxazole and trimethoprim',
  'Condition': 'AcneOff-label',
  'Rating': '9'},
 {'Drug Name': 'Indomethacin', 'Condition': 'Back Pain', 'Rating': '1'},
 {'Drug Name': 'Doxylamine', 'Condition': 'Insomnia', 'Rating': '7'},
 {'Drug Name': 'Sulfamethoxazole and trimethoprim',
  'Condition': 'Urinary Tract Infection',
  'Rating': '10'},
 {'Drug Name': 'Paxlovid', 'Condition': 'COVID-19', 'Rating': '4'},
 {'Drug Name': 'Belsomra', 'Condition': 'Insomnia', 'Rating': '1'},
 {'Drug Name': 'Rexulti',
  'Condition': 'Major Depressive Disorder',
  'Rating': '2'},
 {'Drug Name': 'Sildenafil',
  'Condition': 'Erectile Dysfunction',
  'Rating': '10'},
 {'Drug Name': 'Wegovy',
  'Condition': 'Weight Loss (Obesity/Overweight)',
  'Rating': '10'},
 {'Drug Name': 'Trazodone', 'Condition': 'Sedation', 'Rating': '9'},
 {'Drug Name': 'Junel Fe 24', 'Condition': 'Birth Control', 'Rating': '5'},
 {'Drug Name': 'Verapamil', 'Condition': 'High Blood Pressure', 'Rating': '9'},
 {'Drug Name': 'Levonorgestrel', 'Condition': 'Birth Control', 'Rating': '2'},
 {'Drug Name': 'Empagliflozin',
  'Condition': 'Diabetes, Type 2',
  'Rating': '6'},
 {'Drug Name': 'Hydroxyzine Pamoate', 'Condition': 'Anxiety', 'Rating': '1'},
 {'Drug Name': 'Venlafaxine', 'Condition': 'Depression', 'Rating': '8'},
 {'Drug Name': 'Paragard', 'Condition': 'Birth Control', 'Rating': '7'},
 {'Drug Name': 'Levonorgestrel',
  'Condition': 'Emergency Contraception',
  'Rating': '1'},
 {'Drug Name': 'Dextromethorphan', 'Condition': 'Cough', 'Rating': '8'},
 {'Drug Name': 'Quetiapine', 'Condition': 'Depression', 'Rating': '8'},
 {'Drug Name': 'Bupropion', 'Condition': 'Depression', 'Rating': '1'},
 {'Drug Name': 'Sucralfate', 'Condition': 'GERD', 'Rating': '5'},
 {'Drug Name': 'Keflex', 'Condition': 'Bladder Infection', 'Rating': '10'},
 {'Drug Name': 'Trulicity', 'Condition': 'Diabetes, Type 2', 'Rating': '10'},
 {'Drug Name': 'Buprenorphine & Naloxone',
  'Condition': 'Opioid Use Disorder',
  'Rating': '2'},
 {'Drug Name': 'Tramadol',
  'Condition': 'Restless Legs SyndromeOff-label',
  'Rating': '10'},
 {'Drug Name': 'Sofosbuvir', 'Condition': 'Hepatitis C', 'Rating': '10'},
 {'Drug Name': 'Wellbutrin', 'Condition': 'Depression', 'Rating': '8'},
 {'Drug Name': 'Nitrofurantoin',
  'Condition': 'Urinary Tract Infection',
  'Rating': '9'},
 {'Drug Name': 'Omeprazole',
  'Condition': 'Hiatal HerniaOff-label',
  'Rating': '2'},
 {'Drug Name': 'Effexor', 'Condition': 'Depression', 'Rating': '10'},
 {'Drug Name': 'Zoloft',
  'Condition': 'Social Anxiety Disorder',
  'Rating': '3'},
 {'Drug Name': 'Zyprexa', 'Condition': 'Depression', 'Rating': '1'},
 {'Drug Name': 'Fluoxetine', 'Condition': 'Depression', 'Rating': '9'},
 {'Drug Name': 'Venlafaxine', 'Condition': 'Anxiety', 'Rating': '1'},
 {'Drug Name': 'Geodon', 'Condition': 'Bipolar Disorder', 'Rating': '9'},
 {'Drug Name': 'Metronidazole',
  'Condition': 'Bacterial Vaginosis',
  'Rating': '10'},
 {'Drug Name': 'Yaz', 'Condition': 'Acne', 'Rating': '3'},
 {'Drug Name': 'Namenda', 'Condition': "Alzheimer's Disease", 'Rating': '1'},
 {'Drug Name': 'Semaglutide', 'Condition': 'Diabetes, Type 2', 'Rating': '10'},
 {'Drug Name': 'Quetiapine', 'Condition': 'InsomniaOff-label', 'Rating': '7'},
 {'Drug Name': 'Seroquel', 'Condition': 'Bipolar Disorder', 'Rating': '9'},
 {'Drug Name': 'Sertraline',
  'Condition': 'Anxiety and StressOff-label',
  'Rating': '8'},
 {'Drug Name': 'Dulaglutide', 'Condition': 'Diabetes, Type 2', 'Rating': '1'},
 {'Drug Name': 'Desvenlafaxine',
  'Condition': 'Major Depressive Disorder',
  'Rating': '7'},
 {'Drug Name': 'Escitalopram',
  'Condition': 'Generalized Anxiety Disorder',
  'Rating': '7'},
 {'Drug Name': 'Dexamethasone',
  'Condition': 'Nausea/Vomiting, Chemotherapy Induced',
  'Rating': '10'},
 {'Drug Name': 'Yuvafem', 'Condition': 'Atrophic Vaginitis', 'Rating': '1'},
 {'Drug Name': 'Aripiprazole', 'Condition': 'Bipolar Disorder', 'Rating': '1'},
 {'Drug Name': 'Soma',
  'Condition': 'Nocturnal Leg CrampsOff-label',
  'Rating': '1'},
 {'Drug Name': 'Sertraline',
  'Condition': 'Anxiety and StressOff-label',
  'Rating': '9'},
 {'Drug Name': 'Citalopram', 'Condition': 'Anxiety and Stress', 'Rating': '2'},
 {'Drug Name': 'Junel', 'Condition': 'Birth Control', 'Rating': '1'},
 {'Drug Name': 'Rivaroxaban',
  'Condition': 'Atrial Fibrillation',
  'Rating': '1'},
 {'Drug Name': 'Venlafaxine', 'Condition': 'Depression', 'Rating': '4'},
 {'Drug Name': 'Nitrofurantoin',
  'Condition': 'Urinary Tract Infection',
  'Rating': '1'},
 {'Drug Name': 'Baclofen', 'Condition': 'NeuralgiaOff-label', 'Rating': '1'},
 {'Drug Name': 'Abilify Maintena',
  'Condition': 'Schizophrenia',
  'Rating': '7'},
 {'Drug Name': 'Xofluza', 'Condition': 'Influenza', 'Rating': '9'},
 {'Drug Name': 'Ketorolac', 'Condition': 'Postoperative Pain', 'Rating': '2'},
 {'Drug Name': 'Nortriptyline',
  'Condition': 'Panic DisorderOff-label',
  'Rating': '9'},
 {'Drug Name': 'Nortriptyline',
  'Condition': 'Migraine PreventionOff-label',
  'Rating': '9'},
 {'Drug Name': 'Quetiapine',
  'Condition': 'Generalized Anxiety DisorderOff-label',
  'Rating': '3'},
 {'Drug Name': 'Levonorgestrel',
  'Condition': 'Emergency Contraception',
  'Rating': '1'},
 {'Drug Name': 'Hydromorphone', 'Condition': 'Pain', 'Rating': '6'},
 {'Drug Name': 'Letrozole', 'Condition': 'Breast Cancer', 'Rating': '9'},
 {'Drug Name': 'Levofloxacin', 'Condition': 'Pneumonia', 'Rating': '10'},
 {'Drug Name': 'Plan B',
  'Condition': 'Emergency Contraception',
  'Rating': '9'},
 {'Drug Name': 'Xolair', 'Condition': 'Urticaria', 'Rating': '10'},
 {'Drug Name': 'Tramadol', 'Condition': 'AnxietyOff-label', 'Rating': '9'},
 {'Drug Name': 'Levonorgestrel', 'Condition': 'Birth Control', 'Rating': '7'},
 {'Drug Name': 'Pregabalin', 'Condition': 'Fibromyalgia', 'Rating': '1'},
 {'Drug Name': 'Duloxetine',
  'Condition': 'Generalized Anxiety Disorder',
  'Rating': '10'},
 {'Drug Name': 'Biotin',
  'Condition': 'Dietary Supplementation',
  'Rating': '5'},
 {'Drug Name': 'Bisacodyl', 'Condition': 'Constipation', 'Rating': '5'},
 {'Drug Name': 'Yaz 28', 'Condition': 'Birth Control', 'Rating': '1'},
 {'Drug Name': 'Wegovy',
  'Condition': 'Weight Loss (Obesity/Overweight)',
  'Rating': '9'},
 {'Drug Name': 'Albuterol',
  'Condition': 'Asthma, Maintenance',
  'Rating': '10'},
 {'Drug Name': 'Geodon', 'Condition': 'Bipolar Disorder', 'Rating': '9'},
 {'Drug Name': 'Bisacodyl', 'Condition': 'Constipation', 'Rating': '9'},
 {'Drug Name': 'Ajovy', 'Condition': 'Migraine Prevention', 'Rating': '1'},
 {'Drug Name': 'Aripiprazole',
  'Condition': 'Major Depressive Disorder',
  'Rating': '8'},
 {'Drug Name': 'Prazosin', 'Condition': 'High Blood Pressure', 'Rating': '1'},
 {'Drug Name': 'Hydroxyzine Pamoate', 'Condition': 'Anxiety', 'Rating': '8'},
 {'Drug Name': 'Wellbutrin', 'Condition': 'Depression', 'Rating': '6'},
 {'Drug Name': 'Vraylar', 'Condition': 'Bipolar Disorder', 'Rating': '5'},
 {'Drug Name': 'Ceftriaxone', 'Condition': 'Pneumonia', 'Rating': '1'},
 {'Drug Name': 'Bisacodyl', 'Condition': 'Constipation', 'Rating': '1'},
 {'Drug Name': 'Acyclovir', 'Condition': 'Herpes Simplex', 'Rating': '1'},
 {'Drug Name': 'Escitalopram',
  'Condition': 'Generalized Anxiety Disorder',
  'Rating': '5'},
 {'Drug Name': 'Yaz', 'Condition': 'Birth Control', 'Rating': '1'},
 {'Drug Name': 'Zoloft', 'Condition': 'Depression', 'Rating': '9'},
 {'Drug Name': 'Kyleena', 'Condition': 'Birth Control', 'Rating': '4'},
 {'Drug Name': 'Soliqua', 'Condition': 'Diabetes, Type 2', 'Rating': '2'},
 {'Drug Name': 'Oxycodone and acetaminophen',
  'Condition': 'Pain',
  'Rating': '10'},
 {'Drug Name': 'Quetiapine',
  'Condition': 'Generalized Anxiety DisorderOff-label',
  'Rating': '10'},
 {'Drug Name': 'Zoloft', 'Condition': 'Panic Disorder', 'Rating': '8'},
 {'Drug Name': 'Amitriptyline',
  'Condition': 'InsomniaOff-label',
  'Rating': '8'},
 {'Drug Name': 'Benzonatate', 'Condition': 'Cough', 'Rating': '1'},
 {'Drug Name': 'Levonorgestrel', 'Condition': 'Birth Control', 'Rating': '3'},
 {'Drug Name': 'Phentermine',
  'Condition': 'Weight Loss (Obesity/Overweight)',
  'Rating': '10'},
 {'Drug Name': 'Desvenlafaxine', 'Condition': 'Depression', 'Rating': '7'},
 {'Drug Name': 'Reglan', 'Condition': 'Nausea/Vomiting', 'Rating': '3'},
 {'Drug Name': 'Klonopin', 'Condition': 'Panic Disorder', 'Rating': '10'},
 {'Drug Name': 'Semaglutide', 'Condition': 'Diabetes, Type 2', 'Rating': '5'},
 {'Drug Name': 'Medroxyprogesterone',
  'Condition': 'Birth Control',
  'Rating': '10'},
 {'Drug Name': 'Tretinoin', 'Condition': 'Acne', 'Rating': '10'},
 {'Drug Name': 'Levothyroxine',
  'Condition': 'Underactive Thyroid',
  'Rating': '1'},
 {'Drug Name': 'Vyvanse', 'Condition': 'Binge Eating Disorder', 'Rating': '8'},
 {'Drug Name': 'Modafinil',
  'Condition': 'DepressionOff-label',
  'Rating': '10'},
 {'Drug Name': 'Levonorgestrel', 'Condition': 'Birth Control', 'Rating': '8'},
 {'Drug Name': 'Enbrel', 'Condition': 'Rheumatoid Arthritis', 'Rating': '9'},
 {'Drug Name': 'Suboxone', 'Condition': 'Opioid Use Disorder', 'Rating': '8'},
 {'Drug Name': 'Yasmin', 'Condition': 'Acne', 'Rating': '9'},
 {'Drug Name': 'Ketorolac', 'Condition': 'Pain', 'Rating': '10'},
 {'Drug Name': 'Alprazolam', 'Condition': 'Panic Disorder', 'Rating': '5'},
 {'Drug Name': 'Provigil', 'Condition': 'Narcolepsy', 'Rating': '10'},
 {'Drug Name': 'Promethazine', 'Condition': 'Nausea/Vomiting', 'Rating': '10'},
 {'Drug Name': 'Desvenlafaxine',
  'Condition': 'Major Depressive Disorder',
  'Rating': '3'},
 {'Drug Name': 'Relafen', 'Condition': 'Osteoarthritis', 'Rating': '7'},
 {'Drug Name': 'Paxil', 'Condition': 'Social Anxiety Disorder', 'Rating': '4'},
 {'Drug Name': 'Bisacodyl', 'Condition': 'Constipation', 'Rating': '10'},
 {'Drug Name': 'Seroquel', 'Condition': 'Bipolar Disorder', 'Rating': '2'},
 {'Drug Name': 'Venlafaxine',
  'Condition': 'Bipolar DisorderOff-label',
  'Rating': '7'},
 {'Drug Name': 'Dulaglutide', 'Condition': 'Diabetes, Type 2', 'Rating': '1'},
 {'Drug Name': 'Amitriptyline',
  'Condition': 'InsomniaOff-label',
  'Rating': '2'},
 {'Drug Name': 'Escitalopram',
  'Condition': 'Obsessive Compulsive DisorderOff-label',
  'Rating': '10'},
 {'Drug Name': 'Prednisone', 'Condition': 'Immunosuppression', 'Rating': '1'},
 {'Drug Name': 'Nitrofurantoin',
  'Condition': 'Prevention of Bladder infection',
  'Rating': '7'},
 {'Drug Name': 'Sovaldi', 'Condition': 'Hepatitis C', 'Rating': '10'},
 {'Drug Name': 'Tamsulosin',
  'Condition': 'Urinary Tract StonesOff-label',
  'Rating': '10'},
 {'Drug Name': 'Metoclopramide',
  'Condition': 'Nausea/Vomiting',
  'Rating': '3'},
 {'Drug Name': 'Hydroxyzine', 'Condition': 'Anxiety', 'Rating': '1'},
 {'Drug Name': 'Celexa', 'Condition': 'Depression', 'Rating': '9'},
 {'Drug Name': 'Vraylar', 'Condition': 'Bipolar Disorder', 'Rating': '8'},
 {'Drug Name': 'Fluticasone and salmeterol',
  'Condition': 'Asthma, Maintenance',
  'Rating': '1'},
 {'Drug Name': 'Sulfamethoxazole and trimethoprim',
  'Condition': 'Urinary Tract Infection',
  'Rating': '1'},
 {'Drug Name': 'Misoprostol',
  'Condition': 'AbortionOff-label',
  'Rating': '10'},
 {'Drug Name': 'Vyepti', 'Condition': 'Migraine Prevention', 'Rating': '1'},
 {'Drug Name': 'Keytruda',
  'Condition': 'Squamous Cell Carcinoma',
  'Rating': '1'},
 {'Drug Name': 'Keppra', 'Condition': 'Seizures', 'Rating': '2'},
 {'Drug Name': 'Clonazepam', 'Condition': 'InsomniaOff-label', 'Rating': '1'},
 {'Drug Name': 'Macrobid',
  'Condition': 'Urinary Tract Infection',
  'Rating': '7'},
 {'Drug Name': 'Methylphenidate', 'Condition': 'ADHD', 'Rating': '10'},
 {'Drug Name': 'Desvenlafaxine', 'Condition': 'Depression', 'Rating': '7'},
 {'Drug Name': 'Ketorolac Tromethamine', 'Condition': 'Pain', 'Rating': '1'},
 {'Drug Name': 'Hydrocodone and Acetaminophen',
  'Condition': 'Pain',
  'Rating': '8'},
 {'Drug Name': 'Cymbalta', 'Condition': 'Fibromyalgia', 'Rating': '3'},
 {'Drug Name': 'Imiquimod',
  'Condition': 'Human Papilloma Virus',
  'Rating': '9'},
 {'Drug Name': 'Nexplanon', 'Condition': 'Birth Control', 'Rating': '3'},
 {'Drug Name': 'Belbuca', 'Condition': 'Chronic Pain', 'Rating': '1'},
 {'Drug Name': 'Gabapentin', 'Condition': 'PainOff-label', 'Rating': '1'},
 {'Drug Name': 'Oxycodone and acetaminophen',
  'Condition': 'Pain',
  'Rating': '10'},
 {'Drug Name': 'Repatha',
  'Condition': 'High Cholesterol, Familial Heterozygous',
  'Rating': '9'},
 {'Drug Name': 'Loestrin 24 Fe ', 'Condition': 'Birth Control', 'Rating': '8'},
 {'Drug Name': 'Exemestane', 'Condition': 'Breast Cancer', 'Rating': '8'},
 {'Drug Name': 'Gabapentin',
  'Condition': 'Trigeminal NeuralgiaOff-label',
  'Rating': '8'},
 {'Drug Name': 'Isotretinoin', 'Condition': 'Acne', 'Rating': '8'},
 {'Drug Name': 'Trimethoprim',
  'Condition': 'Bladder Infection',
  'Rating': '3'},
 {'Drug Name': 'Zepbound',
  'Condition': 'Weight Loss (Obesity/Overweight)',
  'Rating': '8'},
 {'Drug Name': 'Jolessa', 'Condition': 'Birth Control', 'Rating': '1'},
 {'Drug Name': 'Levonorgestrel', 'Condition': 'Birth Control', 'Rating': '6'},
 {'Drug Name': 'Depo-Provera', 'Condition': 'Birth Control', 'Rating': '4'},
 {'Drug Name': 'Levonorgestrel', 'Condition': 'Birth Control', 'Rating': '6'},
 {'Drug Name': 'Atogepant',
  'Condition': 'Migraine Prevention',
  'Rating': '10'},
 {'Drug Name': 'Fluticasone',
  'Condition': 'Lichen SclerosusOff-label',
  'Rating': '9'},
 {'Drug Name': 'Epclusa', 'Condition': 'Hepatitis C', 'Rating': '7'},
 {'Drug Name': 'Oxycodone and acetaminophen',
  'Condition': 'Chronic Pain',
  'Rating': '1'},
 {'Drug Name': 'Bupropion', 'Condition': 'Depression', 'Rating': '8'},
 {'Drug Name': 'Vyvanse', 'Condition': 'ADHD', 'Rating': '9'},
 {'Drug Name': 'Nexplanon', 'Condition': 'Birth Control', 'Rating': '5'},
 {'Drug Name': 'Cephalexin', 'Condition': 'Kidney Infections', 'Rating': '10'},
 {'Drug Name': 'Bisacodyl', 'Condition': 'Constipation', 'Rating': '5'},
 {'Drug Name': 'Pristiq',
  'Condition': 'Major Depressive Disorder',
  'Rating': '9'},
 {'Drug Name': 'Repatha',
  'Condition': 'Cardiovascular Risk Reduction',
  'Rating': '2'},
 {'Drug Name': 'Tranexamic acid',
  'Condition': 'MelasmaOff-label',
  'Rating': '10'},
 {'Drug Name': 'Kyleena', 'Condition': 'Birth Control', 'Rating': '5'},
 {'Drug Name': 'Klonopin', 'Condition': 'Panic Disorder', 'Rating': '8'},
 {'Drug Name': 'Levothyroxine',
  'Condition': 'Thyroid Suppression Test',
  'Rating': '3'},
 {'Drug Name': 'Celexa', 'Condition': 'Depression', 'Rating': '3'},
 {'Drug Name': '5-HTP Mood and Stress', 'Condition': 'Anxiety', 'Rating': '7'},
 {'Drug Name': 'Gilenya', 'Condition': 'Multiple Sclerosis', 'Rating': '10'},
 {'Drug Name': 'Sulfamethoxazole and trimethoprim',

# Embeddings + Vector store

#### Import  Libraries

In [21]:
import pandas as pd
from langchain_google_genai import GoogleGenerativeAIEmbeddings

from langchain_chroma import Chroma
from langchain_community.vectorstores import FAISS
from langchain_groq import ChatGroq
from langchain.chains.history_aware_retriever import create_history_aware_retriever
from langchain.chains.combine_documents import create_stuff_documents_chain
from langchain.chains.retrieval import create_retrieval_chain
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.messages import HumanMessage, AIMessage

import os
from dotenv import load_dotenv
load_dotenv()

True

In [22]:
embeddings = GoogleGenerativeAIEmbeddings(model="models/embedding-001")

In [23]:
# vectorstore = FAISS.from_texts(text, embedding=embeddings, metadatas= metadata)
# vectorstore.save_local("reviews_faiss_db")

In [24]:
vectorstore = Chroma.from_texts(text, embedding=embeddings, metadatas= metadata, persist_directory="reviews_db")

### Create Retriever:

In [62]:
retriever = vectorstore.as_retriever()

In [63]:
llm = ChatGroq(model="Gemma2-9b-It", temperature=0)

# Build Chain

In [64]:
prompt_template = """

You are analyzing patient reviews of medications. Answer questions using ONLY the provided reviews.

Guidelines:
- Always mention drug names and conditions
- Include rating numbers (1-10) when available
- Be specific - say "3 out of 5 reviews mentioned..." when possible
- If unsure, say "The reviews don't mention this"

Reviews:
{context}

Question: {input}

Answer clearly and specifically:"""

In [65]:
prompt = ChatPromptTemplate([prompt_template])

In [66]:
document_chain = create_stuff_documents_chain(
    llm=llm,  # Our Groq model
    prompt=prompt  # The template above
)

In [67]:
rag_chain = create_retrieval_chain(
    retriever=retriever,
    combine_docs_chain= document_chain
)

## Invoke the chain:

In [68]:
rag_chain.invoke({"input": "Which drug has the most complaints?"})

{'input': 'Which drug has the most complaints?',
 'context': [Document(id='e975594c-d0bd-48c9-a7fd-3c5a84a12110', metadata={'Condition': 'Postoperative Pain', 'Drug Name': 'Ketorolac', 'Rating': '2'}, page_content='Toradol (ketorolac)"Lots of stomach pains, nausea.   Heartburn.  It caused more pain than relief"'),
  Document(id='aa764e64-8117-40b3-963a-2fa112d66e71', metadata={'Condition': 'NeuralgiaOff-label', 'Drug Name': 'Baclofen', 'Rating': '1'}, page_content='Lioresal (baclofen)"I had  pains in my legs after knee surgery and I took this medicine only one pill 4 times in two days and I have never been so sick in my entire life! I was so sick to my stomach that even water made me even more sick. Whatever I ate or drank would come back up about an hour later. I could barely stand up straight, I was shaking, I had fever and chills, etc. It was horrible! I stopped taking it as soon as this started and then it took another two days to actually completely get out of my system!"'),
  Document(id='30a73e4a-4514-440b-8c90-8e9fbbb0784c', metadata={'Condition': 'Depression', 'Drug Name': 'Bupropion', 'Rating': '1'}, page_content='Wellbutrin (bupropion)"I\'ve taken it for a week now and all its caused was me and my gf to have big fights in public. I already had anger issues. Its worse now. I\'ll stick with it for another week or two, if it doesn\'t get better. I\'m quitting this mess."'),
  Document(id='dfe8bd0a-32cf-422d-8a47-06213f730efd', metadata={'Condition': 'Allergic Rhinitis', 'Drug Name': 'Fexofenadine', 'Rating': '1'}, page_content='Allegra (fexofenadine)"Gave me and my family chest pains. Would not recommend"')],
 'answer': 'Lioresal (baclofen) has the most complaints.  The review describes severe and debilitating side effects including nausea, vomiting, fever, chills, and shaking.  \n'}

In [69]:
result = rag_chain.invoke({"input": "Which drug has the best reviews?"})
result['answer']

'Based on the provided reviews, Pristiq (desvenlafaxine) has the most positive reviews. \n\nTwo reviewers mention significant improvements in their lives while taking Pristiq, with one describing a "renewed life" and another stating it "definitely feel[s] better" in the morning. \n\n'

In [70]:
result = rag_chain.invoke({"input": "calculte the average rating"})
result['answer']

"The reviews don't mention an average rating. \n\n\n\n"

# Pandas Agent

In [71]:


#pip install langchain-experimental

from langchain_experimental.agents import create_pandas_dataframe_agent
agent = create_pandas_dataframe_agent(llm, df, verbose= True, allow_dangerous_code=True)
agent.invoke("what is the average rating")

> Entering new AgentExecutor chain...
Thought: I need to calculate the average of the 'Rating' column.
Action: python_repl_ast
Action Input: df['Rating'].mean()5.974Thought: I now know the final answer
Final Answer: 5.974


> Finished chain.

{'input': 'what is the average rating', 'output': '5.974'}

In [72]:
pandas_agent = create_pandas_dataframe_agent(llm, df, verbose=True, allow_dangerous_code=True)

## Reference Metadata:

In [73]:
from langchain.agents import Tool

In [74]:
review_tool = Tool(
    name= "review_tool",
    func= lambda x: rag_chain.invoke({"input": x}),
     description="Useful for answering medical/natural language questions based on review content, drug effects, descriptions, etc."
)

pandas_tool = Tool(
    name= "pandas_tool",
    func= pandas_agent.invoke,
    description="Useful for answering questions about the structured dataset like record counts, averages, filtering, ratings etc."
)

In [75]:
tools = [ review_tool, pandas_tool]

In [79]:
from langchain.agents import initialize_agent, AgentType

agent = initialize_agent(
    tools=tools,
    llm=llm,
    agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
    verbose=True,
    handle_parsing_errors=True
)

In [77]:
agent.invoke("How many reviews are there?")

> Entering new AgentExecutor chain...
Thought: I need to find the number of records in the dataframe.
Action: python_repl_ast
Action Input: len(df)500Thought: I now know the final answer
Final Answer: 500


> Finished chain.

{'input': 'How many reviews are there?', 'output': 'There are 500 reviews.'}

In [80]:
agent.invoke("What are the common side effects of Mirena ?")

> Entering new AgentExecutor chain...
Thought: I need to look up information about Mirena's side effects.
Action: review_tool
Action Input: Mirena side effects
Observation: {'input': 'Mirena side effects', 'context': [Document(id='b532808b-3cc6-49c2-884d-5a3b97a8e549', metadata={'Condition': 'Birth Control', 'Drug Name': 'Levonorgestrel', 'Rating': '3'}, page_content='Mirena (levonorgestrel)"I used the Mirena as a contraception and as a way to control my uterine bleeding. Was an effective contraception however it did have intolerable side effects. On a positive note I was less mood swingy and weight loss. On the more negative side I felt gradually mildly depressed had a severely reduced energy.  Six weeks after I had the coil inserted I began to have upper back pain, muscle tension which got increasingly worse.  I was getting by by popping pain killers and attending physio, nothing helped. I finally realised I only ever had a bad back since the coil and muscle tension and bad back are listed as side effects, after 7 months I had it removed within 4 weeks my back pan had gone, I felt so relieved. Never again. I have my energy back as well."'), Document(id='fae243d4-582c-4573-b667-3fbed98721fb', metadata={'Condition': 'Birth Control', 'Drug Name': 'Levonorgestrel', 'Rating': '9'}, page_content='Mirena (levonorgestrel)"I took Mirena for 3 years and switch today to paraguard instead. Insertion wasn\'t too painful and hurt much less than the IUD I have now. The removal was actually hurt more) Anyways, the first year I had irregular periods, but no weight gain, no moodiness, no pain during sec, or lack of sex drive-  so that was great. The reason I chose to remove it, is that the last 6 months or so, I had much more spotting, I thought my periods would go away, but they never did, and it became highly unpredictable. I am hoping that if I have to have a period, I\'d like to know when it is, even if it\'s heavier. I am now going to give the Paraguard a try and see how it goes, if the side effects are worse than Mirena, I will likely be switch back."'), Document(id='03a5dd6d-5d3b-4a9e-8b8a-5b60b3b61692', metadata={'Condition': 'Birth Control', 'Drug Name': 'Levonorgestrel', 'Rating': '2'}, page_content='Mirena (levonorgestrel)"I was recommended Mirena after I got a blood clot at 17 years old due to a protein s deficiency, Mirena was my only option. I decided after years of research that it was time to try it out. Having never had kids I was told the insertion and everything would be a little more painful than a mother would experience (my mom was on Mirena) the insertion was painful, but after I was fine. About 3 days later I was in so much pain that I kept throwing up and couldn\'t stand up straight, my gyno said this was normal... I\'ve had my IUD in for 1.5 years, about twice a year a get pain like I did originally. I\'ve noticed mood swings, weight gain and total loss of any sex drive. Only reason I\'ve kept it this long is it\'s my only option"'), Document(id='1875f011-d3f4-44c3-91f0-aa0ca5cd89ba', metadata={'Condition': 'Birth Control', 'Drug Name': 'Levonorgestrel', 'Rating': '1'}, page_content='Mirena (levonorgestrel)"I went to have the Mirena IUD removed 1 1/2 years after placement and my ob/gyn couldn\'t find it to remove it. I have had an ultrasound that turned up nothing and now need an abdominal xray to see if it can be located that way. My insurance won\'t cover any of it until my deductible is met,  so I have to come up with $1000 just to find out, and if they find it, I\'ll need surgery. This "migration and spontaneous expulsion" are more common than the company says. "')], 'answer': "Here are some side effects of Mirena reported in the reviews:\n\n* **Pain:** 3 out of 4 reviews mention pain as a side effect. This includes upper back pain, muscle tension, and pain after insertion. \n* **Mood Changes:** 2 out of 4 reviews mention mood swings or depression as side effects.\n* **Weight Gain:** 1 out of 4 reviews mentions weight gain as a side effect.\n* **Irregular Periods/Spotting:** 2 out of 4 reviews mention irregular periods or increased spotting as side effects.\n* **Loss of Sex Drive:** 1 out of 4 reviews mentions a loss of sex drive. \n\n\nThe reviews don't mention other potential side effects like headaches, nausea, or changes in breast size. \n"}
Thought:Question: What are the common side effects of Mirena ?
Thought: I need to look up information about Mirena's side effects.
Action: review_tool
Action Input: Mirena side effects
Observation: {'input': 'Mirena side effects', 'context': [Document(id='b532808b-3cc6-49c2-884d-5a3b97a8e549', metadata={'Condition': 'Birth Control', 'Drug Name': 'Levonorgestrel', 'Rating': '3'}, page_content='Mirena (levonorgestrel)"I used the Mirena as a contraception and as a way to control my uterine bleeding. Was an effective contraception however it did have intolerable side effects. On a positive note I was less mood swingy and weight loss. On the more negative side I felt gradually mildly depressed had a severely reduced energy.  Six weeks after I had the coil inserted I began to have upper back pain, muscle tension which got increasingly worse.  I was getting by by popping pain killers and attending physio, nothing helped. I finally realised I only ever had a bad back since the coil and muscle tension and bad back are listed as side effects, after 7 months I had it removed within 4 weeks my back pan had gone, I felt so relieved. Never again. I have my energy back as well."'), Document(id='fae243d4-582c-4573-b667-3fbed98721fb', metadata={'Condition': 'Birth Control', 'Drug Name': 'Levonorgestrel', 'Rating': '9'}, page_content='Mirena (levonorgestrel)"I took Mirena for 3 years and switch today to paraguard instead. Insertion wasn\'t too painful and hurt much less than the IUD I have now. The removal was actually hurt more) Anyways, the first year I had irregular periods, but no weight gain, no moodiness, no pain during sec, or lack of sex drive-  so that was great. The reason I chose to remove it, is that the last 6 months or so, I had much more spotting, I thought my periods would go away, but they never did, and it became highly unpredictable. I am hoping that if I have to have a period, I\'d like to know when it is, even if it\'s heavier. I am now going to give the Paraguard a try and see how it goes, if the side effects are worse than Mirena, I will likely be switch back."'), Document(id='03a5dd6d-5d3b-4a9e-8b8a-5b60b3b61692', metadata={'Condition': 'Birth Control', 'Drug Name': 'Levonorgestrel', 'Rating': '2'}, page_content='Mirena (levonorgestrel)"I was recommended Mirena after I got a blood clot at 17 years old due to a protein s deficiency, Mirena was my only option. I decided after years of research that it was time to try it out. Having never had kids I was told the insertion and everything would be a little more painful than a mother would experience (my mom was on Mirena) the insertion was painful, but after I was fine. About 3 days later I was in so much pain that I kept throwing up and couldn\'t stand up straight, my gyno said this was normal... I\'ve had my IUD in for 1.5 years, about twice a year a get pain like I did originally. I\'ve noticed mood swings, weight gain and total loss of any sex drive. Only reason I\'ve kept it this long is it\'s my only option"'), Document(id='1875f011-d3f4-44c3-91f0-aa0ca5cd89ba', metadata={'Condition': 'Birth Control', 'Drug Name': 'Levonorgestrel', 'Rating': '1'}, page_content='Mirena (levonorgestrel)"I went to have the Mirena IUD removed 1 1/2 years after placement and my ob/gyn couldn\'t find it to remove it. I have had an ultrasound that turned up nothing and now need an abdominal xray to see if it can be located that way. My insurance won\'t cover any of it until my deductible is met,  so I have to come up with $1000 just to find out, and if they find it, I\'ll need surgery. This "migration and spontaneous expulsion" are more common than the company says. "')], 'answer': "Here are some side effects of Mirena reported in the reviews:\n\n* **Pain:** 3 out of 4 reviews mention pain as a side effect. This includes upper back pain, muscle tension, and pain after insertion. \n* **Mood Changes:** 2 out of 4 reviews mention mood swings or depression as side effects.\n* **Weight Gain:** 1 out of 4 reviews mentions weight gain as a side effect.\n* **Irregular Periods/Spotting:** 2 out of 4 reviews mention irregular periods or increased spotting as side effects.\n* **Loss of Sex Drive:** 1 out of 4 reviews mentions a loss of sex drive. \n\n\nThe reviews don't mention other potential side effects like headaches, nausea, or changes in breast size. \n"}
Thought:Thought: I now know the common side effects of Mirena based on the reviews.
Final Answer: According to the reviews, common side effects of Mirena include pain (upper back pain, muscle tension, pain after insertion), mood changes (mood swings, depression), weight gain, irregular periods or increased spotting, and loss of sex drive.




> Finished chain.

{'input': 'What are the common side effects of Mirena ?',
 'output': 'According to the reviews, common side effects of Mirena include pain (upper back pain, muscle tension, pain after insertion), mood changes (mood swings, depression), weight gain, irregular periods or increased spotting, and loss of sex drive.'}